/* Auto-generated by build_catalog.py — do not edit directly.
   Edit artist-config.json and re-run build_catalog.py. */
window.ARCHIVE_CONFIG = {
  "artistName": "Jeffrey F. S. Neumann",
  "artistShort": "JFSN",
  "artistActive": "1974–present",
  "siteUrl": "https://jfsn.com",
  "siteTitle": "JFSN Archive",
  "license": "CC BY 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
  "themes": [
    {
      "name": "Mr. Snowmann",
      "displayTitle": "Mr. SNOWmann",
      "description": "A recurring figure — part totem, part pop effigy — assembled from the residue of consumer culture. Across more than a hundred works spanning five decades, the Snowmann shape-shifts and accumulates: a sustained riff on American iconography, assembly, and the act of making something from nothing."
    },
    {
      "name": "Crosses",
      "displayTitle": "Crosses",
      "description": "The cross reduced to its geometry — symmetry, perpendicular meeting, four directions held in tension. Form that carries cultural weight before any specific reading is applied, returned to pure structure and asked to hold whatever the viewer brings."
    },
    {
      "name": "Targets",
      "displayTitle": "Targets",
      "description": "Concentric rings, bull's-eye forms, and range markers appear across dozens of works as compositional anchors and loaded symbols. Precision without declared purpose. The target as both invitation and warning — a form that compels attention before meaning is assigned."
    },
    {
      "name": "Torsos & Faces",
      "displayTitle": "Torsos & Faces",
      "description": "Photographic fragments of the human body — cropped, magnified, repositioned — set against grounds that compete with and complement the figure. Presence through reduction; the body as found material, as much subject as surface."
    },
    {
      "name": "Framed",
      "displayTitle": "Framed Pieces",
      "description": "Works conceived with framing as an integral compositional element — the frame not as neutral container but as collaborator. Edge and interior in negotiation; the boundary of the work as part of the work itself."
    },
    {
      "name": "Studio",
      "displayTitle": "Studio Images",
      "description": "Works photographed in the context of the studio — process images, studies in available light, and the raw material of practice before it becomes exhibition. The space where everything starts, documented at various stages of arrival."
    },
    {
      "name": "Gallery",
      "displayTitle": "Gallery Images",
      "description": "Exhibition views and installation photographs from five decades of showing work. The archive of the archive: spaces, arrangements, and the accumulated evidence of a practice made public and encountered by other eyes."
    },
    {
      "name": "Collaboration",
      "displayTitle": "Collaboration",
      "description": "Works made in collaboration with other artists — shared process, dual authorship, two practices finding common ground."
    },
    {
      "name": "Tracings",
      "displayTitle": "Tracings",
      "description": "Works built from the act of tracing — contour drawn over found imagery, line extracted from photograph or print. A method of close looking that is also a method of possession: the original image remains visible beneath the intervention, neither fully surrendered nor entirely replaced."
    },
    {
      "name": "Art School",
      "displayTitle": "Art School Work",
      "description": "Work made during and around the BFA years at the Cleveland Institute of Art. The foundation built here — printmaking, industrial drawing, material thinking — runs under everything that came after. These pieces catch the practice at the moment of formation: uncertain in the best way, searching, not yet committed to what it would become."
    }
  ],
  "namedSeries": [
    {
      "key": "Guernica",
      "displayTitle": "XXXIII · Guernica",
      "description": "232 works, 1990–2020. Collage, primarily. The recurring elements are compact discs, targets, and warplanes — concentric rings laid against black, red, white, yellow. The planes are drawn from above or from the side, reduced to diagrams. The discs function as bullseyes, as roundels, as shields. American footballs appear. Chess pieces. The compositions tend toward the panoramic: figures scattered across a wide ground, or arranged in friezes. The work is not anti-war. It doesn't illustrate anything. It uses the vocabulary of conflict — ordnance, insignia, game pieces, sport — and holds them flat, side by side, in the grammar of collage."
    }
  ],
  "palette": [
    "red",
    "vermilion",
    "magenta",
    "pink",
    "orange",
    "yellow",
    "ochre",
    "gold",
    "silver",
    "iridescent",
    "white",
    "ivory",
    "black",
    "grey",
    "brown",
    "green",
    "turquoise",
    "blue",
    "ultramarine",
    "purple"
  ],
  "motifs": [
    "compact-disc",
    "vinyl-record",
    "cassette",
    "warplane-topdown",
    "warplane-side",
    "chess-piece",
    "target",
    "bullseye",
    "concentric-rings",
    "roundel",
    "perforated-dots",
    "lace-doily",
    "crown",
    "cross",
    "numerals",
    "fabric-letters",
    "photographic-face",
    "torso",
    "american-football",
    "soccer-ball",
    "lips",
    "honeycomb",
    "gold-leaf",
    "beaded-thread",
    "sequins",
    "ribbon-stripe",
    "polka-dot",
    "grid",
    "vertical-stripes",
    "star",
    "ink-drip",
    "map-fragment",
    "keyboard",
    "tape"
  ],
  "materials": [
    "paper",
    "paint",
    "ink",
    "silver-foil",
    "gold-leaf",
    "cardboard",
    "plastic",
    "lace",
    "resin",
    "cassette",
    "ribbon",
    "keyboard",
    "sequins",
    "tape",
    "canvas"
  ],
  "workTypes": [
    "collage",
    "sculpture",
    "painting",
    "photograph"
  ]
};
