/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './*.html',
    './_shared/*.html',
    './_shared/*.js',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // ── Core design system (Stitch / light)
        "background":             "#fcf9f3",
        "deep-ink":               "#0B0B0B",
        "bone-white":             "#F3F0EA",
        "international-orange":   "#FF6600",
        "orange-ink":             "#B84700",   // accessible orange — text on light bg only (5.07:1 AA); use international-orange for fills/borders/dark-bg text
        "archive-gray":           "#575757",
        "outline-variant":        "#c4c7c7",
        "surface-container-high": "#ebe8e2",
        // ── Material Design tokens (archive, decade pages)
        "primary":                "#000000",
        "secondary":              "#5e5e5e",
        "on-tertiary-container":  "#e05900",
        "on-surface":             "#1c1c18",
        "on-surface-variant":     "#444748",
        "on-background":          "#1c1b1b",
        "on-primary":             "#ffffff",
        "on-secondary":           "#ffffff",
        "outline":                "#747878",
        "surface":                "#fcf9f3",
        "surface-container":      "#f1edec",
        "surface-container-low":  "#f6f3ed",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e5e2e1",
        "surface-dim":            "#dcdad4",
        "surface-tint":           "#5f5e5e",
        "primary-container":      "#1c1b1b",
        // ── Remaining tokens (used on 1–7 pages)
        "on-error":               "#ffffff",
        "error":                  "#ba1a1a",
        "tertiary-fixed-dim":     "#d0c5b3",
        "inverse-on-surface":     "#f3f0ea",
        "secondary-container":    "#fe6500",
      },
      borderRadius: {
        "DEFAULT": "0px",
        "lg":      "0px",
        "xl":      "0px",
        "full":    "9999px",
      },
      spacing: {
        "margin-desktop": "64px",
        "margin-mobile":  "16px",
        "margin-tablet":  "32px",
        "gutter":         "24px",
        "container-max":  "1440px",
        "unit":           "8px",
        "xs":             "4px",
        "sm":             "12px",
        "md":             "24px",
        "lg":             "48px",
        "xl":             "80px",
        "base":           "8px",
      },
      fontFamily: {
        "display-lg":      ["Playfair Display", "Georgia", "serif"],
        "headline-lg":     ["Playfair Display", "Georgia", "serif"],
        "headline-lg-mobile": ["Playfair Display", "Georgia", "serif"],
        "headline-md":     ["Playfair Display", "Georgia", "serif"],
        "nav-link":        ["Inter", "sans-serif"],
        "label-caps":      ["Inter", "sans-serif"],
        "label-lg":        ["Inter", "sans-serif"],
        "label-md":        ["Inter", "sans-serif"],
        "body-lg":         ["Inter", "sans-serif"],
        "body-md":         ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg":      ["64px",  { lineHeight: "1.1",  letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg":     ["48px",  { lineHeight: "56px", fontWeight: "600" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-md":     ["28px",  { lineHeight: "1.3",  fontWeight: "500" }],
        "nav-link":        ["14px",  { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-caps":      ["12px",  { lineHeight: "16px", letterSpacing: "0.1em",  fontWeight: "600" }],
        "label-lg":        ["14px",  { lineHeight: "1.2",  letterSpacing: "0.05em", fontWeight: "600" }],
        "label-md":        ["12px",  { lineHeight: "1.2",  letterSpacing: "0.05em", fontWeight: "500" }],
        "body-lg":         ["18px",  { lineHeight: "28px", fontWeight: "400" }],
        "body-md":         ["16px",  { lineHeight: "24px", fontWeight: "400" }],
      },
      aspectRatio: {
        "3/4": "3 / 4",
      },
    },
  },
  plugins: [],
}
